### ISSUE TITLE
quit()した後、ターミナルに入力文字が表示されなくなる

### ISSUE THREAD

**Issue by Pon2G** [kumavale/rust-tetris#12]
Linux環境で発生する現象です。
ゲームオーバー時、およびQキー押下により`quit()`が呼ばれゲームを終了した後、ターミナルに入力文字が表示されません。
[https://doc.rust-lang.org/std/process/fn.exit.html](https://doc.rust-lang.org/std/process/fn.exit.html)に記述されているように、`std::process::exit(0)`によりプロセスを終了した際に`Getch`構造体のデストラクタが呼ばれることなく終了しているためと思われます。
実際、以下のように意図的に`drop`させてから`quit()`すると、終了後も問題なく動作します。

```diff
diff --git a/chapter07/src/main.rs b/chapter07/src/main.rs
index e290e0f..a7bf271 100644
--- a/chapter07/src/main.rs
+++ b/chapter07/src/main.rs
@@ -98,6 +98,7 @@ fn main() {
                 draw(&game);
             }
             Ok(Key::Char('q')) => {
+                drop(g);
                 quit();
             }
             _ => (),  // 何もしない
```

私の経験が浅いため、`gameover`関数側については、どこで`Getch`構造体を`drop`すべきかわかっていません。

**Comment by kumavale** [comment]
報告ありがとうございます！
確かにデストラクタが呼ばれていないことが原因のようです。
`getch()`が入力待ち状態で別スレッドから`drop`させる方法が私にも分からないので、対処法としては以下のようなことを考えています。

`std::process::exit(0)`で終了させるのではなく、<kbd>q</kbd>キーでループを抜けて終了処理を行う。  
そしてゲームオーバー時は <kbd>q</kbd>キーの入力を促す。
